version: '3.8'

services:
  postgres-dev:
    image: postgres:16-alpine
    container_name: grocery-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DEV_DB:-grocery_management}
      POSTGRES_USER: ${POSTGRES_USER:-grocery_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-grocery_password}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - grocery-network
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-grocery_user} -d ${POSTGRES_DEV_DB:-grocery_management}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: grocery-backend-dev
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=grocery-postgres-dev;Port=5432;Database=${POSTGRES_DEV_DB:-grocery_management};Username=${POSTGRES_USER:-grocery_user};Password=${POSTGRES_PASSWORD:-grocery_password}
    volumes:
      - ./backend:/app
      - dotnet_packages:/root/.nuget/packages
    networks:
      - grocery-network
    depends_on:
      postgres-dev:
        condition: service_healthy
    stdin_open: true
    tty: true

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: grocery-frontend-dev
    restart: unless-stopped
    ports:
      - "3001:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:5001/api}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - grocery-network
    depends_on:
      - backend-dev
    stdin_open: true
    tty: true

  adminer:
    image: adminer:latest
    container_name: grocery-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - grocery-network
    depends_on:
      - postgres-dev

volumes:
  postgres_dev_data:
    driver: local
  dotnet_packages:
    driver: local
  frontend_node_modules:
    driver: local

networks:
  grocery-network:
    driver: bridge
