FROM mcr.microsoft.com/dotnet/sdk:9.0 AS development

RUN apt-get update && \
    apt-get install -y \
    curl \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*



WORKDIR /app

ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:5000
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
ENV DOTNET_WATCH_SUPPRESS_BROWSER_REFRESH=true

EXPOSE 5000

COPY *.sln ./
COPY Domain/Domain.csproj ./Domain/
COPY Application/Application.csproj ./Application/
COPY Infraestructure/Infraestructure.csproj ./Infraestructure/
COPY Presentation/Presentation.csproj ./Presentation/

RUN dotnet restore

COPY . .

CMD ["dotnet", "watch", "run", "--project", "Presentation", "--urls", "http://0.0.0.0:5000"]
